// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("WikiDataTypeProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("WikiDataTypeProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing WikiDataTypeProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "WikiDataTypeProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "WikiDataTypeProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing WikiDataTypeProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
